name: Java CI with Maven

on:
  push:
    branches: [ "main", "localtest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.7
          distribution: adopt
          maven-version: '3.9.1'
      - name: Print Java and Maven versions
        run: |
          echo "Java version: ${{ env.JAVA_HOME }}"
          mvn -version
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-uri: ${{ secrets.MONGO_URI }}
          mongodb-version: latest
      - name: Build with Maven
        run: |
          mvn -version
          mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn test --file pom.xml -Dtest=GodisControllerTest
        env:
          MONGODB_URI: ${{ secrets.MONGO_URI }}