name: Java CI with Maven

on:
  push:
    branches: [ "main", "localtest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.7
          distribution: adopt

      - name: Install Maven 3.9.1
        run: |
            wget https://apache.osuosl.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xf apache-maven-3.9.1-bin.tar.gz
            export PATH=$PWD/apache-maven-3.9.1/bin:$PATH

      - name: Print Java and Maven versions
        run: |
          echo "Java version: ${{ env.JAVA_HOME }}"
          mvn -version

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-uri: ${{ secrets.MONGO_URI }}
          mongodb-version: latest

      - name: Build with Maven
        run: |
          mvn -version
          mvn -B package --file pom.xml
        env:
          MONGODB_URI: ${{ secrets.MONGO_URI }}

      - name: Test with Maven
        run: mvn test --file pom.xml -Dtest=GodisControllerTest
        env:
          MONGODB_URI: ${{ secrets.MONGO_URI }}