name: Java CI with Maven

on:
  push:
    branches: [ "main", "localtest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-uri: ${{ secrets.MONGO_URI }}
          distribution: 'ubuntu1804'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn test --file pom.xml
        env:
          MONGODB_URI: ${{ secrets.MONGO_URI }}
      - name: Run GodisControllerTest
        run: mvn -Dtest=GodisControllerTest test --file pom.xml
        env:
            MONGODB_URI: ${{ secrets.MONGO_URI }}